import PDFDocument from 'pdfkit';
import {
  generateProfitLossData,
  generateExpenseReportData,
  formatCurrency,
  formatPercentage,
  formatReportDate,
  type ProfitLossData,
  type ExpenseReport,
} from './report-utils';

/**
 * Generate Profit & Loss PDF report
 */
export async function generateProfitLossPDF(
  companyId: string,
  fiscalYear: number,
  companyName: string
): Promise<Buffer> {
  // Get data
  const data = await generateProfitLossData(companyId, fiscalYear, companyName);

  return new Promise((resolve, reject) => {
    try {
      // Create PDF document
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });

      // Collect chunks
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(data.companyName, { align: 'center' });
      doc.moveDown(0.5);
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(`Profit & Loss Statement - ${data.fiscalYear}`, { align: 'center' });
      doc.moveDown(0.3);
      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`Generated: ${formatReportDate(data.generatedDate)}`, { align: 'center' });

      doc.moveDown(2);

      // Revenue Section
      drawSectionHeader(doc, 'REVENUE');
      doc.moveDown(0.5);

      data.revenue.items.forEach((item) => {
        drawLineItem(doc, item.category, item.amount, item.percentage);

        // Draw subcategories if present
        if (item.subcategories) {
          item.subcategories.forEach((sub) => {
            drawSubLineItem(doc, sub.name, sub.amount);
          });
        }
      });

      doc.moveDown(0.5);
      drawTotalLine(doc, 'Total Revenue', data.revenue.total);
      doc.moveDown(1.5);

      // Expenses Section
      drawSectionHeader(doc, 'EXPENSES');
      doc.moveDown(0.5);

      data.expenses.items.forEach((item) => {
        drawLineItem(doc, item.category, item.amount, item.percentage);

        if (item.subcategories) {
          item.subcategories.forEach((sub) => {
            drawSubLineItem(doc, sub.name, sub.amount);
          });
        }
      });

      doc.moveDown(0.5);
      drawTotalLine(doc, 'Total Expenses', data.expenses.total);
      doc.moveDown(1.5);

      // Net Profit Section
      const profitColor = data.netProfit >= 0 ? '#10b981' : '#ef4444';
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor(profitColor)
        .text('NET PROFIT', 50, doc.y, { continued: true, width: 350 });
      doc
        .fillColor(profitColor)
        .text(formatCurrency(data.netProfit, true), { align: 'right', width: 150 });

      doc.moveDown(0.5);
      doc
        .fontSize(11)
        .fillColor('black')
        .font('Helvetica')
        .text('Profit Margin', 50, doc.y, { continued: true, width: 350 });
      doc.text(formatPercentage(data.profitMargin), { align: 'right', width: 150 });

      // Footer
      doc
        .fontSize(8)
        .fillColor('#666666')
        .text(
          'This report was automatically generated by AI Accounting Assistant',
          50,
          doc.page.height - 50,
          { align: 'center', width: doc.page.width - 100 }
        );

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate Expense Report PDF
 */
export async function generateExpenseReportPDF(
  companyId: string,
  fiscalYear: number,
  companyName: string,
  fiscalQuarter?: number
): Promise<Buffer> {
  // Get data
  const data = await generateExpenseReportData(companyId, fiscalYear, companyName, fiscalQuarter);

  return new Promise((resolve, reject) => {
    try {
      // Create PDF document
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });

      // Collect chunks
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(data.companyName, { align: 'center' });
      doc.moveDown(0.5);
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(
          `Expense Report - ${data.fiscalYear}${data.fiscalQuarter ? ` Q${data.fiscalQuarter}` : ''}`,
          { align: 'center' }
        );
      doc.moveDown(0.3);
      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`Generated: ${formatReportDate(data.generatedDate)}`, { align: 'center' });

      doc.moveDown(2);

      // Expenses by Category
      drawSectionHeader(doc, 'EXPENSES BY CATEGORY');
      doc.moveDown(0.5);

      data.expensesByCategory.forEach((item) => {
        drawLineItem(doc, item.category, item.amount, item.percentage);

        if (item.subcategories) {
          item.subcategories.forEach((sub) => {
            drawSubLineItem(doc, sub.name, sub.amount);
          });
        }
      });

      doc.moveDown(0.5);
      drawTotalLine(doc, 'Total Expenses', data.totalExpenses);
      doc.moveDown(2);

      // Top Expenses
      drawSectionHeader(doc, 'TOP 10 INDIVIDUAL EXPENSES');
      doc.moveDown(0.5);

      // Table header
      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('Description', 50, doc.y, { continued: true, width: 250 });
      doc.text('Amount', { continued: true, width: 100, align: 'right' });
      doc.text('Date', { width: 100, align: 'right' });
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(0.3);

      // Table rows
      doc.fontSize(9).font('Helvetica');
      data.topExpenses.forEach((expense) => {
        const description =
          expense.description.length > 40
            ? expense.description.substring(0, 37) + '...'
            : expense.description;

        doc.text(description, 50, doc.y, { continued: true, width: 250 });
        doc.text(formatCurrency(expense.amount), { continued: true, width: 100, align: 'right' });
        doc.text(formatReportDate(expense.date), { width: 100, align: 'right' });
        doc.moveDown(0.5);
      });

      // Footer
      doc
        .fontSize(8)
        .fillColor('#666666')
        .text(
          'This report was automatically generated by AI Accounting Assistant',
          50,
          doc.page.height - 50,
          { align: 'center', width: doc.page.width - 100 }
        );

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Helper function to draw section header
 */
function drawSectionHeader(doc: PDFKit.PDFDocument, title: string) {
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#1f2937')
    .text(title, { underline: true });
}

/**
 * Helper function to draw line item
 */
function drawLineItem(
  doc: PDFKit.PDFDocument,
  label: string,
  amount: number,
  percentage?: number
) {
  const y = doc.y;
  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('black')
    .text(label, 50, y, { continued: true, width: 300 });

  doc.text(formatCurrency(amount), { continued: true, width: 100, align: 'right' });

  if (percentage !== undefined) {
    doc.text(formatPercentage(percentage), { width: 100, align: 'right' });
  }

  doc.moveDown(0.3);
}

/**
 * Helper function to draw sub-line item (indented)
 */
function drawSubLineItem(doc: PDFKit.PDFDocument, label: string, amount: number) {
  const y = doc.y;
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#666666')
    .text(`  • ${label}`, 60, y, { continued: true, width: 290 });

  doc.text(formatCurrency(amount), { width: 100, align: 'right' });

  doc.moveDown(0.2);
}

/**
 * Helper function to draw total line
 */
function drawTotalLine(doc: PDFKit.PDFDocument, label: string, amount: number) {
  const y = doc.y;

  // Draw line above total
  doc.moveTo(50, y).lineTo(550, y).stroke();
  doc.moveDown(0.3);

  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor('black')
    .text(label, 50, doc.y, { continued: true, width: 300 });

  doc.text(formatCurrency(amount, true), { width: 100, align: 'right' });

  doc.moveDown(0.3);

  // Draw double line below total
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke();
}
